### ISSUE TITLE
Example of skip policy configuration in this example

### ISSUE THREAD

**Issue by jaybytez** [spring-guides/gs-batch-processing#13]
I used this example as a reference for a quick (and successful) implementation of Spring batch in a Spring boot application.  The doc/reference mainly shows skip policy configuration in XML, where would be the proper placement for skipping records within the sample?  Thanks for your time.

**Comment by gregturn** [comment]
@mminella Care to comment?

**Comment by gregturn** [comment]
With no further feedback, I'm closing the ticket.
