### ISSUE TITLE
Adding my own JobParameters - How to replace/intercept the 'jobLauncher.run(...)' method?

### ISSUE THREAD

**Issue by sixman9** [spring-guides/gs-batch-processing#15]
Hi,
I'm new to Spring batch but your great tutorial is allowing me to explore the JobExplorer APIs for finished Job instances (excuse the pun).

My question is, **how can I add my own JobParameters to the JobLauncher.run(...) invocation of the "importUserJob" Job bean**? 

I'm not entirely sure how to override the job's execution, your 'jobLauncher.run(...)' call is a little bit 'hidden' within your Spring-derived dependency library, at 'JobLauncherCommandLineRunner.execute()', within 'spring-boot-autoconfigure-1.5.2.RELEASE.jar'.

Am I right in assuming that, just having the bean references to the Job/JobLauncher, in BatchConfiguration.java, isn't enough for me to add my own parameters to that job? **Do I need to just, explicitly, execute my own Job instances via JobLauncher.run(...), where I can also supply my own 'JobParameters' instance?**

The 'JobExecutionListenerSupport.beforeJob(JobExecution)' method is actually called too *'late'*, as, a Job instanced has already been started, and passed an immutable JobParameter object, at that time.

**Comment by benas** [comment]
This is better asked on stackoverflow, but I will answer your question here and close the issue.

> My question is, how can I add my own JobParameters to the JobLauncher.run(...) invocation of the "importUserJob" Job bean?

You can pass job parameters on the CLI like:

```
java -jar target/gs-batch-processing-0.1.0.jar param1=value1 param2=value2
```

Spring Boot will parse those arguments and pass them as parameters to your job. You can find more details in the [Batch Applications](https://docs.spring.io/spring-boot/docs/2.3.1.RELEASE/reference/html/howto.html#howto-batch-applications) section of the reference documentation.

If you really want to add job parameters programmatically, you can do something like:

```java
import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.JobParametersBuilder;
import org.springframework.batch.core.launch.JobLauncher;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) throws Exception {
		// disable job launch at startup with spring.batch.job.enabled=false (otherwise the job will be executed twice)
		ConfigurableApplicationContext applicationContext = SpringApplication.run(DemoApplication.class, args);

		JobLauncher jobLauncher = applicationContext.getBean(JobLauncher.class);
		Job job = applicationContext.getBean(Job.class);

		JobParameters jobParameters = new JobParametersBuilder()
				// add parameters from args
				// add additional parameters
				.toJobParameters();

		jobLauncher.run(job, jobParameters);
	}

}
```

But this approach defeats the boot purpose in the first place (aka automatically load the application context, parse arguments and pass them as job parameters, launch the job, etc).
