### ISSUE TITLE
Guide without Spring Boot

### ISSUE THREAD

**Issue by harbulot** [spring-guides/gs-batch-processing#19]
This is just a suggestion to improve the documentation, partly related to spring-guides/getting-started-guides#9.

It would be great to explain what happens in this code:

```java
@SpringBootApplication
public class Application {
    public static void main(String[] args) throws Exception {
        SpringApplication.run(Application.class, args);
    }
}
```

I understand the main reason to have Getting Started guides mostly based around Spring Boot is to avoid having to re-explain data sources and so on, but I'm talking about what's specific to Spring Batch: more specifically, how to make the jobs actually run.

Thankfully, I've found this external article: http://malsolo.com/blog4java/?p=260

I've been able to adapt it to my examples like so:

```java
@Component
public class HelloApplication {
    @Autowired
    private JobLauncher jobLauncher;

    @Autowired
    private Job importUserJob;

    @Autowired
    public static void main(String[] args) throws Exception {
        try (AnnotationConfigApplicationContext springContext = new AnnotationConfigApplicationContext(
                ConfigBean.class)) {
            HelloApplication main = springContext
                    .getBean(HelloApplication.class);

            main.jobLauncher.run(main.importUserJob,
                    new JobParameters());
        }
    }
}
```

It would be great to elaborate a bit more in the guides about where the `JobLauncher.run(...)` is implied, and under which circumstances certain things will be configured or called.

What can often be tricky is to distinguish between what's automatically picked up by non-Boot Spring (e.g. regular `@ComponentScan`) and may need to be explicitly enabled or disabled, and what's automatically done because of Spring Boot.

**Comment by realsony** [comment]
2 years later and still open & unhandled :(

**Comment by gregturn** [comment]
I believe https://spring.io/guides/gs/batch-processing/#_make_the_application_executable explains the point of `@SpringBootApplication`.
