### ISSUE TITLE
Unnecessary Asciidoctor tags in code samples

### ISSUE THREAD

**Issue by PeterWippermann** [spring-guides/gs-batch-processing#27]
I was wondering what these "tags" in your code samples are about:
https://github.com/spring-guides/gs-batch-processing/blob/5fa701cdc146070d47fb51c9f5c4659c338cf58a/complete/src/main/java/hello/BatchConfiguration.java#L36

Took me a while to find out these are artifacts of your AsciiDoc markup. Since [in the tutorial](https://spring.io/guides/gs/batch-processing/#_put_together_a_batch_job) you include the source code file  as a whole, the tags are also included. That way they are useless, but visible. And funnily, your tags [have been copied all over the Internet](https://www.google.de/search?q="readerwriterprocessor") :-D

Maybe you can remove these AsciiDoc tags from the source?

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-batch-processing/commit/7ab425a723f776aff0660ec6c7f71ba89d5447aa and https://github.com/spring-guides/gs-batch-processing/commit/ba6b41e91c4278f4e498bec6734048c3b90b6837.
