### ISSUE TITLE
Use SpringApplication.exit and System.exit to ensure that the JVM exits upon job completion

### ISSUE THREAD

**Issue by wilkinsona** [spring-guides/gs-batch-processing#40]
Please see https://github.com/spring-projects/spring-boot/issues/22092 for some background. The guide should encourage the use of [Spring Boot's Application Exit](https://docs.spring.io/spring-boot/docs/2.3.x/reference/htmlsingle/#boot-features-application-exit) support.

**Comment by florentbo** [comment]
As you mentioned in [https://github.com/spring-projects/spring-boot/issues/22092#issuecomment-648944874](url) , another alternative is switching back to Spring Boot 2.2's behaviour where this bootstrapping was performed synchronously by adding `spring.data.jpa.repositories.bootstrap-mode=default` to `application.properties`

**Comment by wilkinsona** [comment]
I do. Switching back to the default bootstrap mode is only a point solution. Anything else that starts one or more non-daemon threads that are tidied up by a call to `close()` on the application context would still have the same problem. Using `SpringApplication.exit` will close the context.

**Comment by izeye** [comment]
I created https://github.com/spring-guides/gs-batch-processing/pull/41 to try to resolve this.
