### ISSUE TITLE
Java 11 doesn't work..!

### ISSUE THREAD

**Issue by keunoh** [spring-guides/gs-batch-processing#46]
Two days ago I completed this guide with Java 11 version.
But I retried it today but It didn't work.
There are compile error:
[class file has wrong version 61.0, should be 55.0 ]

Is it only can tested by Java 17? 

AS-IS my pom.xml file:
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.6</version>
		<relativePath/> 
</parent>

TOBE :
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.0</version>
		<relativePath/> 
</parent>

if I change version
JobBuilder class and StepBuilder class are having more constructor.

return new JobBuilder("importUserJob", jobRepository)
                .incrementer(new RunIdIncrementer())
                .listener(listener)
                .flow(step1)
                .end()
                .build();

So this code cannot be resolved!
because when I use 2.7.6 version JobBuilder class has only one constructor

public JobBuilder(String name) {
    super(name);
}

How can I resolve this problem?

**Comment by florentbo** [comment]
It's using Spring Boot 3 now. So It's only runnable with Java 17

**Comment by keunoh** [comment]
got it thanks
