### ISSUE TITLE
Gradle build for the complete project is broken

### ISSUE THREAD

**Issue by psoares** [spring-guides/gs-batch-processing#47]
A typo in the `gradle.build` prevents the project from compiling.
`mvn install` fails with the following error:

```
Plugin [id: 'org.springframework.boot', version: '3,0.0'] was not found in any of the following sources:
```

The coma in `3,0.0` needs to be replaced by a dot and become `3.0.0` (or `3.0.2` at this time).

**Comment by psoares** [comment]
@sdeleuze please have a look when it makes sense...

**Comment by fmbenhassine** [comment]
@psoares Thank you for raising this!

We will update the guide accordingly.

**Comment by Buzzardo** [comment]
Fixed in https://github.com/spring-guides/gs-batch-processing/pull/51

I could have pushed to main, but I think it's good to have a PR to match the issue, even though that means merging my own PR.

**Comment by psoares** [comment]
@Buzzardo maybe you should cancel the PR #49 I had submitted too?

**Comment by Buzzardo** [comment]
Done. We'll bump the version at the next minor version. We rarely worry about the patch versions, unless it's something like a security fix.
