### ISSUE TITLE
JobExecutionListenerSupport is deprecated

### ISSUE THREAD

**Issue by psoares** [spring-guides/gs-batch-processing#48]
`JobExecutionListenerSupport`, used in `JobCompletionNotificationListener` is now deprecated and can be replaced by `implements JobExecutionListener` instead.

**Comment by psoares** [comment]
@fmbenhassine, @Buzzardo any interest in updating this? If not you can close the issue and PR #50.

**Comment by fmbenhassine** [comment]
Yes we are interested! Thank you for the PR! We will merge it when updating the guide.

**Comment by Buzzardo** [comment]
I went ahead and merged it. Since it had no conflicts, it was two button clicks to merge it.

Thanks to both of you (one for doing it and one for letting me know I could merge it). :)
