### ISSUE TITLE
Update Spring Boot to latest version

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-batch-processing#53]
Update the guide to use the most recent Spring Boot version.

Files that require changes are:
`initial/build.gradle`
`initial/pom.xml`
`complete/build.gradle`
`complete/pom.xml`

**Comment by robertmcnees** [comment]
Latest version of Spring Boot can be found on [start.spring.io](https://start.spring.io/).  Milestones (M) and SNAPSHOT releases should not be used in the guide.

**Comment by florentbo** [comment]
I create the following PR: https://github.com/spring-guides/gs-batch-processing/pull/54 related to this issue

**Comment by robertmcnees** [comment]
Hi @florentbo.  Thanks for the PR!  Looks good to me.
